version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/db 
    environment:
      - DEBUG=0
      - DATABASE_URL=sqlite:///db/database.db  

volumes:
  sqlite_data:
